title: Debabrata Ghosh
logo: /assets/img/SelfImage2.png
description: Tech lead of testing team | Learning codings on Artificial Intelligence and Machine Learning
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
